### ISSUE TITLE
Add movie functionality

### ISSUE THREAD

**Issue by Genide** [Oncorporation/CastorLazyPack#1]
The existing movie commands could be much better with 2 additions.

1. Allow the movie commands ($movie, $movyt, $movtw) play without additional parameters. This would play the full video without any repeat.
`$movie(D:\Streaming\Videos\test.mp4)`
2. Allow the movie commands to specify decimal seconds. This would allow a user to more precisely control which where a video starts and ends.
`$movie(D:\Streaming\Videos\test.mp4, 0, 12.5)`

**Comment by Oncorporation** [comment]
1. Not done with this.. but I have been looking at it for a while. Personally, I just use defaults in my command settings. The reason for the duration limit is that many streamers may want to give users the ability to play movies and it would be annoying if someone loaded up a 2hr feature film.

2. These are actually in milliseconds, I converted to seconds for simplicity, but will add partial seconds to DURATION

I am unsure if decimal seconds is easier than milliseconds for the users. So, this isn't technically a hurdle, more of a preference on how it is implemented.  Open to opinions!

**Comment by Oncorporation** [comment]
Changes are in, the full video length did not get done, but Decimal seconds are in.

Unfortunately, the way parameters work in SL Chatbot, we can't have one command with optional parameters. We have to make multiple commands because $arg1 and $argl1 are required if they are in the command line.

So I cant make it $command($arg1,$arg2) and then say !command one  , it has to be !command one two
