### ISSUE TITLE
Incorrect Folder Name

### ISSUE THREAD

**Issue by Genide** [Oncorporation/CastorLazyPack#3]
Installing 1.5 does not replace the existing script. Instead, it creates a new misnamed script folder. 
![image](https://user-images.githubusercontent.com/10857365/53844532-9a0b6780-3f6b-11e9-843c-b51a81df0a27.png)

**Comment by Oncorporation** [comment]
well this is embarrassing...
Castorr is the original creator of the script and I have been working from his version. So it was originally "Castorr's Lazy Pack"

I had locally renamed it to Castor as a streamer and to keep from overwriting his version in order to compare changes, test, review documentation, styling, etc.

In honor of Castorr, the correct folder name is CastorrsLazyPack. 

It seems version 1.4, 1,5 and now 1.5.01 are using CastorrsLazyPack and that should be the name moving forward.

**Comment by Genide** [comment]
Then please update all the script shortcuts. They all still point to **CastorLazyPack**, instead of **CastorrsLazyPack**. This results in an unusable browser source.

![image](https://user-images.githubusercontent.com/10857365/54475957-a9897c80-47c5-11e9-878a-02a653d8deac.png)

C:\Users\SOME_NAME\AppData\Roaming\Streamlabs\Streamlabs Chatbot\Services\Scripts\ **CastorLazyPack**\index.html
